# https://travis-ci.org/dryproject/libdry
language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script:
  - ./autogen.sh
script:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ./configure && make && make check; fi
branches:
  only:
    - master
    - coverity

# https://scan.coverity.com/projects/3281
env:
  global:
  - secure: "dORyAvPHmnAwVdA4f7JA2WkMOxNAflY5Fi4qHL/9wpWlo5bmj547IY33srcIqAlPI0iGAMOTPXLIVjDJk8qEkWS4ecX2WFYgxIBPVSlNbcTsGi3R1Z6pCAzP+2fVFcuR+a3NLp/FLS28LEHWnYG93m0SRnhcDCtM7pX4fQj60CY=" # COVERITY_SCAN_TOKEN
addons:
  coverity_scan:
    project:
      name: dryproject/libdry
    notification_email: arto@bendiken.net
    build_command_prepend: cov-configure --comptype gcc --compiler $CC && ./configure
    build_command: make && make check
    branch_pattern: coverity
